#!/bin/bash
echo "╔══════════════════════════════════════════════╗"
echo "║   ShadowStrike v56.1 — Справка              ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "КОМАНДЫ:"
echo "  shadow scan <url>         Полное сканирование"
echo "  shadow passive            Пассивный сканер (прокси)"
echo "  shadow c2 <port>          C2 сервер"
echo "  shadow hunt <tech> <url>  Охота на технологию"
echo "  shadow predict <url>      Предсказать уязвимости"
echo "  shadow whisper <domain>   Пассивная разведка"
echo "  shadow echo <url>         Детект WAF"
echo "  shadow lie <url>          Детектор лжи сервера"
echo "  shadow maze               Создать лабиринт"
echo "  shadow decode <string>    Декодер"
echo "  shadow evolution          Запустить эволюцию"
echo "  shadow help               Эта справка"
echo ""
echo "ПРИМЕРЫ:"
echo "  shadow scan http://testphp.vulnweb.com"
echo "  shadow hunt grafana http://target.com:3000"
echo "  shadow whisper target.com"
